# Generated by Django 6.0.3 on 2026-03-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_file_attachment_message_is_sticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='academic_title',
            field=models.CharField(choices=[('Mr', 'Monsieur'), ('Dr', 'Docteur'), ('Pr', 'Professeur')], default='Mr', max_length=10),
        ),
    ]
