# Generated by Django 6.0.3 on 2026-03-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teacherprofile_academic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='academic_title',
            field=models.CharField(choices=[('Mr', 'Monsieur'), ('Mme', 'Madame'), ('Dr', 'Docteur'), ('Pr', 'Professeur')], default='Mr', max_length=10),
        ),
    ]
