# Generated by Django 6.0.3 on 2026-03-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_groupreadreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sticker_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
