# Generated by Django 6.0.3 on 2026-03-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_actual_duration_minutes_booking_is_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='custom_subjects',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
