# Generated by Django 6.0.3 on 2026-03-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='call_room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='call_status',
            field=models.CharField(blank=True, choices=[('started', 'En attente'), ('ongoing', 'En cours'), ('ended', 'Terminé'), ('missed', 'Manqué'), ('declined', 'Refusé')], default='started', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='call_type',
            field=models.CharField(blank=True, choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'Nouveau Message'), ('booking_confirmed', 'Cours Confirmé'), ('booking_cancelled', 'Cours Annulé'), ('new_booking', 'Nouveau Cours'), ('incoming_call', 'Appel Entrant')], max_length=20),
        ),
    ]
